services:
  app:
    image: node:18
    command: sh -c "npm ci && npm run dev"
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./.npmrc:/app/.npmrc
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./tsconfig.json:/app/tsconfig.json
      - ./src:/app/src
      - ./docker-compose/app/node_modules:/app/node_modules
    environment:
      MONGO_URL: mongodb://mongo/ozmap
    depends_on:
      mongo:
        condition: service_healthy
  mongo:
    image: mongo:7
    restart: always
    command: --quiet
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/ozmap --quiet
    volumes:
      - ./docker-compose/mongo/data/db:/data/db
